使用 xctheos.h 文件实现语法高亮，且与原 md 兼容
FIXME: 速度太慢, 调用后无法直接 debug,编译任然会添加此文件

diff --git a/bin/md b/bin/md
--- a/bin/md
+++ b/bin/md
@@ -643,6 +643,127 @@ function doesFileContain() # args: filePath, pattern
 	echo $funcReturn
 }
 
+function findFileDir() #currentDirectory #filename
+{
+    local currentDirectory=$1
+    local findFile=$2
+
+    for file in `ls "$currentDirectory"`; do
+        if [[ -d "$currentDirectory/$file" ]]; then
+            findFileDir "$currentDirectory/$file" $findFile
+        fi
+
+        if [[ -f "$currentDirectory/$file" ]]; then
+            if [ "$file" == "$findFile" ]; then
+                echo "$currentDirectory"
+                break
+            fi
+        fi
+    done
+}
+
+# 预处理 xm 中的 xctheos 宏
+function xctheos() # args: filePath
+{
+    local headerPath=`findFileDir "$PROJECT_DIR" "xctheos.h"`
+    
+    if [[ ! -d $headerPath ]]; then
+        panic 1 '🌀🌀🌀🌀FUNC: findFileDir() - Find "xctheos.h" faild!🌀🌀🌀🌀'
+    fi
+
+    local filePath=$1
+    local filename=${file##*/}
+    local tempDirs=`mktemp -d -t $scriptName`
+    local newFile="${filename%.*}.m"
+    local newFilePath="$tempDirs/$newFile"
+    local newFilePathBak="${newFilePath}bak" 
+    local resultPath=$filePath
+    local rand="@`date +%s`${RANDOM}@"
+
+    copyFile "$filePath" "$newFilePathBak"
+    copyFile "$filePath" "$newFilePath"
+    local currentDate=`date +%m%d%H%M%S`
+    copyFile "$resultPath" "${filePath}.${currentDate}.bak"
+
+    sed -i '' '1 d' $newFilePath
+    eval "sed -e 's/^\ *#import\ /${rand}import\ /' -i \"\" $newFilePath"
+    eval "sed -e 's/^\ *#define\ /${rand}define\ /' -i \"\" $newFilePath"
+   
+    sed -i ""  "1 i\\
+    #import \"xctheos.h\"
+    " $newFilePath 
+
+    clang -E -DXcodeTheos=1 $newFilePath -o $resultPath -I$headerPath
+    copyFile "$resultPath" "${filePath}cl.bak"
+    eval "sed -e 's/^${rand}import\ /#import\ /' -i \"\" $resultPath"
+    eval "sed -e 's/^${rand}define\ /#define\ /' -i \"\" $resultPath"
+
+    # sed -e 's/^#\ [0-9].*$//' -i "" $resultPath
+    while [[ `head -n 1 $resultPath` =~ ^#\ [0-9]+\ \" ]];
+    do
+        sed -i '' '1 d' $resultPath
+    done
+    copyFile "$resultPath" "${filePath}xm.bak"
+    echo $newFilePathBak
+}
+
+# xm 文件编译时取消 target 选择,编译后恢复
+# FIXME: 速度太慢, 调用后无法直接 debug,编译任然会添加此文件
+function xmPbx() # args: file
+{
+    local projectPath="$PROJECT_FILE_PATH/project.pbxproj"
+    local file=$1
+    local begin='/* Begin '
+    local buildFileSection='PBXBuildFile section */'
+    local sourcesBuildPhaseSection='PBXSourcesBuildPhase section */'
+    local end='/* End ' 
+
+    local isBuildFileSection=0
+    local isSourcesBuildPhaseSection=0
+
+    local delLinesPath="${projectPath}.lines"
+    local length=0
+    local lineNum=1
+
+    echo "">$delLinesPath
+    cat $projectPath | while read line; do
+        if [[ $line =~  "${begin}${buildFileSection}" ]]; then
+            isBuildFileSection=1
+        elif [[ $line =~  "${end}${buildFileSection}" ]]; then
+            isBuildFileSection=0
+        elif [ $isBuildFileSection == 1 ]; then
+            if [[ $line =~ "/* ${file} in Sources */" ]]; then
+                sed -i '' "1 i\\
+                $lineNum
+                " $delLinesPath
+
+                length=`expr 1 + $length`
+            fi
+        elif [[ $line =~  "${begin}${sourcesBuildPhaseSection}" ]]; then
+            isSourcesBuildPhaseSection=1
+        elif [[ $line =~  "${end}${sourcesBuildPhaseSection}" ]]; then
+            isSourcesBuildPhaseSection=0
+        elif [ $isSourcesBuildPhaseSection == 1 ]; then
+            if [[ $line =~ "/* ${file} in Sources */" ]]; then
+                sed -i '' "1 i\\
+                $lineNum
+                " $delLinesPath
+
+                length=`expr 1 + $length`
+            fi;
+        fi
+        lineNum=`expr 1 + $lineNum`
+    done
+    
+    cat $delLinesPath | while read line; do
+        local del=`expr 0 + $((line))`
+        if [[ $del -gt 0 ]]; then
+            eval "sed -i '' '$del d' $projectPath"
+        fi
+    done
+    rm $delLinesPath
+}
+
 #预处理xm、x文件
 function Processor()
 {
@@ -660,10 +781,43 @@ function Processor()
 	  	if [[ -d "$currentDirectory/$file" ]]; then
 	  		Processor "$logosProcessor" "$currentDirectory/$file"
 	  	elif [[ "$extension" == "xm" ]]; then
+            # copyFile "$PROJECT_FILE_PATH/project.pbxproj" "$PROJECT_FILE_PATH/project.pbxproj.bak" 
+            # xmPbx "$file"
+
 			if [[ ! -f "$currentDirectory/${file%.*}.mm" ]] || [[ `ls -l "$currentDirectory/${file%.*}.mm" | awk '{ print $5 }'` < 10 ]] || [[ `stat -f %c "$currentDirectory/$file"` > `stat -f %c "$currentDirectory/${file%.*}.mm"` ]]; then
 	  			echo "Logos Processor: $filename -> ${filename%.*}.mm..."
-	  			logosStdErr=$(("$logosProcessor" "$currentDirectory/$file" > "$currentDirectory/${file%.*}.mm") 2>&1) || \
+                
+				local headerPath=`findFileDir "$PROJECT_DIR" "xctheos.h"`
+				echo "Logos headerPath: $headerPath"
+     			if [[ -d $headerPath ]]; then
+	                sed -i ""  "1 i\\
+	                //
+	                " "$currentDirectory/$file" 
+
+	                local new=`xctheos "$currentDirectory/$file"`
+		  			logosStdErr=$(("$logosProcessor" "$currentDirectory/$file" > "$currentDirectory/${file%.*}.mm") 2>&1)
+
+	                set -x
+	                local error=$?
+
+	                if [ -f $new ]; then
+	                    copyFile "$new" "$currentDirectory/$file"
+	                    rm -rf "${new%/*}"
+	                else
+	                    echo "🌀🌀🌀🌀No"
+	                fi
+
+	                if [ $logosStdErr ]; then
+	                   panic $error "Failed Logos Processor: $logosStdErr" 
+	                fi
+	                set +x
+	                sed -i '' '1 d' "$currentDirectory/$file"
+				else
+					logosStdErr=$(("$logosProcessor" "$currentDirectory/$file" > "$currentDirectory/${file%.*}.mm") 2>&1) || \
 					panic $? "Failed Logos Processor: $logosStdErr"
+				fi
+
+
 			fi
 
 	  	elif [[ "$extension" == "x" ]]; then
